schema_version = "1.0.0"

id = "render_notifications_extension"
version = "1.2.3"
name = "Render Notifications"
tagline = "Notifies you via Discord, desktop, or webhook on render events"
maintainer = "Michael Mosako (JimmyNoStar)"
type = "add-on"
website = "https://github.com/JimmyNos/Render-Notifications"
tags = ["Render", "System"]
blender_version_min = "5.1.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

platforms = ["windows-x64"]
wheels = [
  "./wheels/aiohappyeyeballs-2.6.1-py3-none-any.whl",
  "./wheels/aiohttp-3.13.3-cp313-cp313-win_amd64.whl",
  "./wheels/aiosignal-1.4.0-py3-none-any.whl",
  "./wheels/attrs-26.1.0-py3-none-any.whl",
  "./wheels/audioop_lts-0.2.2-cp313-abi3-win_amd64.whl",
  "./wheels/colorama-0.4.6-py2.py3-none-any.whl",
  "./wheels/discord_py-2.7.1-py3-none-any.whl",
  "./wheels/frozenlist-1.8.0-cp313-cp313-win_amd64.whl",
  "./wheels/idna-3.11-py3-none-any.whl",
  "./wheels/loguru-0.6.0-py3-none-any.whl",
  "./wheels/multidict-6.7.1-cp313-cp313-win_amd64.whl",
  "./wheels/propcache-0.4.1-cp313-cp313-win_amd64.whl",
  "./wheels/yarl-1.23.0-cp313-cp313-win_amd64.whl",
  "./wheels/notify_py-0.3.43-py3-none-any.whl",
  "./wheels/win32_setctime-1.2.0-py3-none-any.whl",
  "./wheels/loguru-0.6.0-py3-none-any.whl",
]

[permissions]
network = "Needed to send notifications via webhooks and Discord"

# Optional: advanced build settings.
# https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "resources/images/readme",
  "Templates/"
]